Alta Batch 4/Phase 1/Week 4/Day 4/Live_code/project_livecode/livecode/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'livecode'
urlpatterns = [
    path('', views.barang, name = 'home'),
    path('home/', views.barang, name = 'home'),
    path('barang/', views.barang, name = 'barangs'),
    path('blog/<int:barang_id>', views.detail, name='details'),
]

Alta Batch 4/Phase 1/Week 4/Day 4/Live_code/project_livecode/project_livecode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('livecode.urls')),
]

Alta Batch 4/Phase 1/Week 4/Day 4/Live_code/project_livecode/livecode/models.py
from django.db import models

# Create your models here.

class Barang(models.Model):
    Gambar            = models.CharField(max_length = 200)
    Nama              = models.CharField(max_length = 200)
    Harga             = models.CharField(max_length = 200)
    Deskripsi1        = models.CharField(max_length = 200)
    Deskripsi2        = models.CharField(max_length = 200,default='')
    Deskripsi3        = models.CharField(max_length = 200,default='')
    

Alta Batch 4/Phase 1/Week 4/Day 4/Live_code/project_livecode/livecode/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Barang

# Create your views here.

def home(request):
    return render(request, 'home.html',{})

def barang(request):
    barang = Barang.objects.all()
    return render(request, 'home.html',{'barangs':barang})
    
def detail(request, barang_id):
    barangs = get_object_or_404(Barang,pk = barang_id)
    return render(request, 'details.html',{'barangs': barangs})

Alta Batch 4/Phase 1/Week 4/Day 4/Live_code/project_livecode/livecode/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <title>{% block Title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="container-fluid headatas">
            <div class="row align-items-center">
                <div class="col-md-2 col-sm-12 tokoonline">
                    <a>Toko Online</a>
                </div>
                <div class="col-md-10 sisa_header">
                    <div>
                        <ul class="header-nav__list1 list-unstyled">
                            <li>
                                <a href="{% url 'livecode:home' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'livecode:home' %}">Input Baru</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row topatas">
            <div class="col-md-4"></div>
            <div class="col-md-4 jarak_kotak">
                <div class="kotak">
                    <img src="{{barangs.Gambar}}">
                    <div class='detailss'>
                        <h3>{{barangs.Nama}}</h3>
                        <h4>{{barangs.Harga}}</h4>
                        <p>Deskripsi Produk : </p>
                        <div class='deskripsi_barang'>
                            <ul>
                                <li>
                                    <p>{{barangs.Deskripsi1}}</p>
                                </li>
                                <li>
                                    <p>{{barangs.Deskripsi2}}</p>
                                </li>
                                <li>
                                    <p>{{barangs.Deskripsi3}}</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
</body>
</html>

Alta Batch 4/Phase 1/Week 4/Day 4/Live_code/project_livecode/livecode/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <title>{% block Title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="container-fluid headatas">
            <div class="row align-items-center">
                <div class="col-md-2 col-sm-12 tokoonline">
                    <a>Toko Online</a>
                </div>
                <div class="col-md-10 sisa_header">
                    <div>
                        <ul class="header-nav__list1 list-unstyled">
                            <li>
                                <a href="{% url 'livecode:home' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'livecode:home' %}">Input Baru</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row topatas">
            {% for barang in barangs%}
            <div class="col-md-4 jarak_kotak">
                <div class="kotak">
                    <img src="{{barang.Gambar}}">
                    <div class='detailss'>
                        <h3>{{barang.Nama}}</h3>
                        <h4>{{barang.Harga}}</h4>
                        <a href="{% url 'livecode:details' barang.id %}">Lihat Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>